### ISSUE TITLE
Quimica - MismaNacionalidad

### ISSUE THREAD

**Issue by luchoxx87** [ET12DE1Computacion/Fulbo12#3]
Se pretende conocer si un `Futbolista` tiene la misma Nacionalidad que otro `Futbolista`.
Recomiendo que se implemente primero el método `bool MismaNacionalidad(Persona)` en `Persona`:
```csharp
// Clase Persona
bool MismaNacionalidad(Persona otra)
```
y se implemente de igual forma en Futbolista:
```csharp
// Clase Futbolista
bool MismaNacionalidad(Futbolista otro)
```
Ejemplos de salidas
```csharp
// Devuelve true porque ambos son argentinos
diegoMaradona.MismaNacionalidad(lioMessi);

// Devuelve false porque cr7 es portugués
lioMessi.MismaNacionalidad(cr7);
```

**Comment by luchoxx87** [comment]
@Liono02 o @MMorandiniGit ¿quién se ve haciendolo primero en el transcurso de este finde?

> 
> 
> Se pretende conocer si un `Futbolista` tiene la misma Nacionalidad que otro `Futbolista`. Recomiendo que se implemente primero el método `bool MismaNacionalidad(Persona)` en `Persona`:
> 
> ```cs
> // Clase Persona
> bool MismaNacionalidad(Persona persona)
> ```
> 
> y se implemente de igual forma en Futbolista:
> 
> ```cs
> // Clase Futbolista
> bool MismaNacionalidad(Futbolista futbolista)
> ```

**Comment by Liono02** [comment]
Profe,ahi envie el commit del método de MismaNacionalidad,dígame si le
llega por favor.
Desde ya,muchas gracias!!

**Comment by luchoxx87** [comment]
No veo ningún commit @Liono02 o algún repo tuyo forkeado (como hiciste cuando agregaste filas en el proyecto de sql).

Recorda que podes colaborar con este proyecto haciéndote un fork y después con pull request contra tu fork. [link de utilidad](https://sqldbawithabeard.com/2019/11/29/how-to-fork-a-github-repository-and-contribute-to-an-open-source-project/)

**Comment by Liono02** [comment]
Listo,creo que ahora si está publicado.
perdón 😅

**Comment by luchoxx87** [comment]
Ahi lo vi, no pasa nada @Liono02 , gracias a vos por tu colaboración. Chusmea porfas lo que te puse en #4

**Comment by luchoxx87** [comment]
Buenas @Liono02, vi los cambios que sugeriste; te di el feedback en #5 ; te recomiendo porfas que veas lo que puse ahí y hagas las correcciones haciendo commit y push sobre el branch que propusiste para el PR.
